//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratoria
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public System.DateTime date_start { get; set; }
        public string code { get; set; }
        public System.DateTime date_end { get; set; }
        public int id_laborant { get; set; }
        public int id_service { get; set; }
        public int id_patient { get; set; }
    
        public virtual patient patient { get; set; }
        public virtual service service { get; set; }
        public virtual user user { get; set; }
    }
}
